#!/bin/bash

#SBATCH --account=def-gberseth
#SBATCH --nodes=1
#SBATCH --gres=gpu:1
#SBATCH --ntasks=1
#SBATCH --mem=32G
#SBATCH --time=24:00:00
#SBATCH --cpus-per-task=8
#SBATCH -o /scratch/fmohamed/slurm-%j.out  # Write the log on scratch

# module load cuda/11.4.2 
module load apptainer

export SINGULARITY_BIND="/etc"
export prj_path="/home/fmohamed/projects/def-gberseth/fmohamed/surprise-adaptive-agents"

apptainer exec --nv -H $prj_path -B  $prj_path:/workdir  $prj_path/test.sif\
  python $1 $2 $3 $4 $5 $6 $7 $8 $9 ${10} ${11}
