#!/bin/bash

#SBATCH --partition=lab-real
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --gres=gpu:1
#SBATCH --mem=100G
#SBATCH --time=18:00:00
#SBATCH --cpus-per-task=4
#SBATCH -o /network/scratch/r/roger.creus-castanyer/slurm-%j.out  # Write the log on scratch

# 1. Load your environment
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/nvidia
module load anaconda/3
conda activate /home/mila/r/roger.creus-castanyer/anaconda3/envs/surprise_adapt

# 4. Launch your job
python3 $1 --env-id $2 --model $3 --buffer-type $4 --seed $5 $6 $7 $8 $9 ${10} ${11} ${12} ${13} ${14} ${15}