#!/bin/bash
#SBATCH --partition=long                               # Ask for unkillable job
#SBATCH --cpus-per-task=2
#SBATCH --gpus-per-node=1                                         # Ask for 1 GPU
#SBATCH --mem=40G                                                # Ask for 10 GB of RAM
#SBATCH --time=24:00:00             
#SBATCH --exclude=cn-g[001-029],cn-b[001-005],cn-i001,cn-j001,kepler5,cn-e[002-003],cn-d[003-004],cn-d[001-002]
#SBATCH -o /network/scratch/r/roger.creus-castanyer/slurm-%j.out  # Write the log on scratch

# 1. Load your environment
module load anaconda/3
conda activate /home/mila/r/roger.creus-castanyer/anaconda3/envs/surprise_adapt

source ../vulkan/1.3.224.1/setup-env.sh

python3 $1 --env-id $2 --model $3 --buffer-type $4 --seed $5 $6 $7 $8 $9