#!/bin/bash
#SBATCH --partition=lab-real                               # Ask for unkillable job
#SBATCH --cpus-per-task=4
#SBATCH --gpus-per-node=1                                         # Ask for 1 GPU
#SBATCH --mem=100G                                                # Ask for 10 GB of RAM
#SBATCH --time=72:00:00                                          # Ask for 6 CPUs
#SBATCH -o /network/scratch/r/roger.creus-castanyer/slurm-%j.out  # Write the log on scratch

# 1. Load your environment
module load anaconda/3
#module load cuda/11.7

conda activate /home/mila/r/roger.creus-castanyer/anaconda3/envs/surprise_adapt

#export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CONDA_PREFIX/lib/

# 4. Launch your job, tell it to save the model in $SLURM_TMPDIR
#    and look for the dataset into $SLURM_TMPDIR
python3 scripts/dqn_smirl.py --config=configs/Atari_SAv2_delta.json --run_mode=local --exp_name=SA_v2_delta_final --training_processor_type=gpu --log_comet=true --random_seeds=3