#!/bin/bash
#SBATCH --partition=lab-real                               # Ask for unkillable job
#SBATCH --cpus-per-task=8
#SBATCH --gpus-per-node=1                                         # Ask for 1 GPU
#SBATCH --mem=100G                                                # Ask for 10 GB of RAM
#SBATCH --time=72:00:00                                          # Ask for 6 CPUs
#SBATCH -o /network/scratch/r/roger.creus-castanyer/slurm-%j.out  # Write the log on scratch

# 1. Load your environment
module load anaconda/3
conda activate /home/mila/r/roger.creus-castanyer/anaconda3/envs/surprise_adapt

source ../vulkan/1.3.224.1/setup-env.sh

python3 $1 --env-id $2 --model $3 --buffer-type $4 --seed $5 $6 $7 $8 $9